---

- name: Import variables for suseLinux
  tags: always
  ansible.builtin.include_vars:
    file: vars/suselinux.yml

- name: Download ISOs
  when: suse_iso
  tags: suse_iso
  ansible.builtin.import_tasks:
    file: suse_isos.yml

- name: Import suse cloud images
  when: suse_image
  tags: suse_image
  ansible.builtin.include_tasks:
    file: suse_import.yml
