---

- name: Import qcow2 images | x86_64
  when: suse_amd64
  community.proxmox.proxmox_template:
    api_host: "{{ proxmox_api_url }}"
    api_user: "{{ proxmox_api_user }}"
    api_port: "{{ proxmox_api_port }}"
    api_token_id: "{{ proxmox_token_id }}" # Make sure values is not full string as per proxmox e.g user@pam!token_name only token_name is variable
    api_token_secret: "{{ proxmox_api_token_secret }}"
    content_type: import
    validate_certs: "{{ validate_certs }}"
    node: "{{ ansible_host }}"
    storage: proxmox_nfs
    url: "{{ suse_image_url }}{{ item.version }}.{{ item.release }}/appliances/openSUSE-{{ item.osname }}-{{ item.version }}.{{ item.release }}-Minimal-VM.x86_64-Cloud.qcow2"
    force: false
    timeout: 1800
    state: present
  loop: "{{ suse_releases }}"
  loop_control:
    label: "suse-{{ item.version }}-{{ item.osname }}-x86_64-qcow2"
  become: false
  run_once: true
  delegate_to: localhost

- name: Import qcow2 images | aarch64
  when: suse_arm64
  community.proxmox.proxmox_template:
    api_host: "{{ proxmox_api_url }}"
    api_user: "{{ proxmox_api_user }}"
    api_port: "{{ proxmox_api_port }}"
    api_token_id: "{{ proxmox_token_id }}" # Make sure values is not full string as per proxmox e.g user@pam!token_name only token_name is variable
    api_token_secret: "{{ proxmox_api_token_secret }}"
    content_type: import
    validate_certs: "{{ validate_certs }}"
    node: "{{ ansible_host }}"
    storage: proxmox_nfs
    url: "{{ suse_image_url }}{{ item.version }}.{{ item.release }}/appliances/openSUSE-{{ item.osname }}-{{ item.version }}.{{ item.release }}-Minimal-VM.aarch64-Cloud.qcow2"
    force: false
    timeout: 1800
    state: present
  loop: "{{ suse_releases }}"
  loop_control:
    label: "suse-{{ item.version }}-{{ item.osname }}-aarch64-qcow2"
  become: false
  run_once: true
  delegate_to: localhost
