---

- name: Check ansible version
  tags: always
  ansible.builtin.assert:
    that: ansible_version.full is version_compare(min_ansible_version, '>=')
    fail_msg: "You must use Ansible {{ min_ansible_version }} or greater"
    success_msg: "This role is running a supported version of ansible {{ ansible_version.full }} >= {{ min_ansible_version }}"

- name: Get proxmox version
  ansible.builtin.shell: "pveversion | cut -d/ -f2"
  changed_when: false
  register: discovered_proxmox_version

- name: Ensure only supported version
  ansible.builtin.assert:
    that: discovered_proxmox_version.stdout is version_compare('9', '>=')
    fail_msg: "Sorry Proxmox VE {{ discovered_proxmox_version.stdout }} is not supported"

- name: Run post install settings on node
  tags: post_install
  ansible.builtin.import_tasks:
    file: post_install.yml

- name: Create api user for steps
  when: create_api_user
  tags: user
  ansible.builtin.import_tasks:
    file: token_user.yml

- name: Generate API token
  tags: token
  ansible.builtin.import_tasks:
    file: generate_token.yml

- name: Add resource pools
  tags: pools
  ansible.builtin.import_tasks:
    file: resource_pools.yml

- name: Add Storage - Backup
  when: backup_storage
  tags: backup
  ansible.builtin.import_tasks:
    file: storage/backup.yml

- name: Add Storage - Iscsi
  when: iscsi_storage
  tags: iscsi
  ansible.builtin.import_tasks:
    file: storage/iscsi.yml

- name: Add Storage - nfs
  when: nfs_storage
  tags: nfs
  ansible.builtin.import_tasks:
    file: storage/nfs.yml

- name: Add ubuntu ISO files
  when: ubuntu_iso or ubuntu_image
  tags: ubuntu
  ansible.builtin.import_tasks:
    file: ubuntulinux/main.yml

- name: Add AlmaLinux OSs to system
  when: alma_iso or alma_image
  tags: alma
  ansible.builtin.import_tasks:
    file: almalinux/main.yml

- name: Add Amazon2023 OS to system
  when: amazon2023_image
  tags: amazon23
  ansible.builtin.import_tasks:
    file: amazon2023/main.yml

- name: Add Oracle Linux OSs to system
  when: oracle_iso or oracle_image
  tags: oracle
  ansible.builtin.import_tasks:
    file: oraclelinux/main.yml

- name: Add RockyLinux OSs to system
  when: rocky_iso or rocky_image
  tags: rocky
  ansible.builtin.import_tasks:
    file: rockylinux/main.yml

- name: Add SuseLinux OSs to system
  when: suse_iso or suse_image
  tags: suse
  ansible.builtin.import_tasks:
    file: suselinux/main.yml

- name: Setup cluster
  when: ansible_hostname in groups['master_node']
  tags: cluster_setup
  ansible.builtin.import_tasks:
    file: cluster_setup.yml

- name: Run undo settings on node
  tags: undo
  ansible.builtin.import_tasks:
    file: undo.yml

- name: Delete current user token
  tags: always
  ansible.builtin.command: "pveum user token delete {{ proxmox_api_user }} {{ proxmox_token_id }} "
  changed_when: discovered_delete_token.rc == 0
  failed_when: discovered_delete_token.rc not in [ 0, 255 ]
  register: discovered_delete_token
