---

- name: Import qcow2 images | x86_64
  when: ubuntu_amd64
  community.proxmox.proxmox_template:
    api_host: "{{ proxmox_api_url }}"
    api_user: "{{ proxmox_api_user }}"
    api_port: "{{ proxmox_api_port }}"
    api_token_id: "{{ proxmox_token_id }}" # Make sure values is not full string as per proxmox e.g user@pam!token_name only token_name is variable
    api_token_secret: "{{ proxmox_api_token_secret }}"
    content_type: import
    validate_certs: "{{ validate_certs }}"
    node: "{{ ansible_host }}"
    storage: proxmox_nfs
    url: "{{ ubuntu_image_url }}{{ item.os_version }}/cloud/x86_64/images/ubuntuLinux-{{ item.os_version }}-GenericCloud-latest.x86_64.qcow2"
    force: false
    timeout: 1800
    state: present
  loop: "{{ ubuntu_releases }}"
  loop_control:
    label: "ubuntu-{{ item.os_version }}-x86_64-qcow2"
  become: false
  run_once: true
  delegate_to: localhost

- name: Import qcow2 images | aarch64
  when: ubuntu_arm64
  community.proxmox.proxmox_template:
    api_host: "{{ proxmox_api_url }}"
    api_user: "{{ proxmox_api_user }}"
    api_port: "{{ proxmox_api_port }}"
    api_token_id: "{{ proxmox_token_id }}" # Make sure values is not full string as per proxmox e.g user@pam!token_name only token_name is variable
    api_token_secret: "{{ proxmox_api_token_secret }}"
    content_type: import
    validate_certs: "{{ validate_certs }}"
    node: "{{ ansible_host }}"
    storage: proxmox_nfs
    url: "{{ ubuntu_image_url }}{{ item.os_version }}/cloud/aarch64/images/ubuntuLinux-{{ item.os_version }}-GenericCloud-latest.aarch64.qcow2"
    force: false
    timeout: 1800
    state: present
  loop: "{{ ubuntu_releases }}"
  loop_control:
    label: "ubuntu-{{ item.os_version }}-aarch64-qcow2"
  become: false
  run_once: true
  delegate_to: localhost
