---

- name: Import variables for debianLinux
  tags: always
  ansible.builtin.include_vars:
    file: vars/debianlinux.yml

- name: Download ISOs
  when: debian_iso
  tags: debian_iso
  ansible.builtin.import_tasks:
    file: debian_isos.yml

- name: Import debian cloud images
  when: debian_image
  tags: debian_image
  ansible.builtin.import_tasks:
    file: debian_import.yml
